#!/usr/bin/env bash
#bash script that configures new ubuntu machine to respect requirements
sudo apt-get update -y
sudo apt-get install nginx -y

ufw allow 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html 

sudo service nginx start
