#!/usr/bin/env bash
#bash script that configures new ubuntu machine to respect requirements
sudo apt-get update -y
sudo apt-get install ngix -y

ufw allow 'Nginx HTTP'

echo "Hello World!" > /var/www/html/index.nginx-debian.html

sudo service nginx start
