#!/usr/bin/env bash
#finding out what's keeping my ubuntu container's nginx installation
#from listening on port 80.

rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
