#!/usr/bin/env bash
#script that print "Best School" ten times
i=0
while [ $i -lt 10 ]; do 
	if [ $i -eq 3 ]; then
		echo "Bad Luck"
	elif [ $i -eq 7 ]; then
		echo "Good luck"
	else
		echo "Best School"
	fi
	((i++))
done
