#!/usr/bin/env bash
#script that print "Best School" ten times
i=1
while [ $i -le 20 ]; do 
	if [ $i -eq 4 ]; then
		echo "$i"
		echo "bad luck from China"
	elif [ $i -eq 9 ]; then
		echo "$i"
		echo "bad luck from Japan"
	elif [ $i -eq 17 ]; then
		echo "$i"
		echo "badluck from Italy"
	else
		echo "$i"
	fi
	((i++))
done
