#!/usr/bin/env bash
#script that prints hours and minutes of a clock
hour=0
while [ $hour -le 12 ]; do
	echo "Hour: $hour"
	minute=1
	while [ $minute -le 59 ]; do
		echo "$minute"
		((minute++))
	done
	((hour++))
done
